image: archlinux/base

stages:
    - build

build:
    stage: build
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel --noconfirm
        - pacman -S rust --noconfirm 
    script:
        - cd monoalphabetic-substitution-ciphers/
        - cd substitution/
        - cargo build
        - cargo test
        - cd ../
        - cd frequency-analysis/
        - cargo build
        - cargo test
        - cd ../../
    artifacts:
        paths:
            - monoalphabetic-substitution-ciphers/substitution/target/debug/substitution 
            - monoalphabetic-substitution-ciphers/frequency-analysis/target/debug/frequency-analysis 
