image: archlinux/base


stages:
    - builds
    - tests


monoalphabetic-substitution-cipher-build:
    stage: builds
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/monoalphabetic-substitution-cipher
        - cargo build


monoalphabetic-substitution-cipher-frequency-analysis-build:
    stage: builds
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/frequency-analysis
        - cargo build


monoalphabetic-substitution-cipher-test:
    stage: tests
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/monoalphabetic-substitution-cipher
        - cargo test


monoalphabetic-substitution-cipher-frequency-analysis-test:
    stage: tests
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/frequency-analysis
        - cargo test
