image: archlinux/base


stages:
    - format
    - builds
    - unit-tests
    - integration-tests


format:
    stage: format
    before_script:
    - pacman -Sy --noconfirm
    - pacman -S rust diffutils gawk grep --noconfirm
    script:
    - for i in $( du -a . | awk '{print $2}' | grep -i ".rs$" ); do
    - cp $i temp.txt
    - rustfmt $i
    - cmp $i temp.txt
    - done
 

monoalphabetic-substitution-cipher-build:
    stage: builds
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/monoalphabetic-substitution-cipher
        - cargo build


monoalphabetic-substitution-cipher-frequency-analysis-build:
    stage: builds
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/frequency-analysis
        - cargo build


monoalphabetic-substitution-cipher-unit-test:
    stage: unit-tests
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/monoalphabetic-substitution-cipher
        - cargo test


monoalphabetic-substitution-cipher-frequency-analysis-unit-test:
    stage: unit-tests
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/frequency-analysis
        - cargo test


monoalphabetic-substitution-cipher-encryption-integration-test:
    stage: integration-tests 
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust diffutils --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/monoalphabetic-substitution-cipher
        - cargo build --release
        - target/release/monoalphabetic-substitution-cipher --key ../examples/The-Adventures-of-Sherlock-Holmes.key --input ../examples/The-Adventures-of-Sherlock-Holmes.plaintext > testing.ciphertext
        - cmp --silent ../examples/The-Adventures-of-Sherlock-Holmes.ciphertext testing.ciphertext


monoalphabetic-substitution-cipher-decryption-integration-test:
    stage: integration-tests 
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust diffutils --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/monoalphabetic-substitution-cipher
        - cargo build --release
        - target/release/monoalphabetic-substitution-cipher --decipher --key ../examples/The-Adventures-of-Sherlock-Holmes.key --input ../examples/The-Adventures-of-Sherlock-Holmes.ciphertext > testing.plaintext
        - cmp --silent ../examples/The-Adventures-of-Sherlock-Holmes.plaintext testing.plaintext


monoalphabetic-substitution-cipher-frequency-analysis-integration-test:
    stage: integration-tests
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust diffutils --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/frequency-analysis
        - cargo build --release
        - target/release/frequency-analysis --input ../examples/The-Adventures-of-Sherlock-Holmes.ciphertext > testing.frequency-analysis
        - cmp --silent ../examples/The-Adventures-of-Sherlock-Holmes.frequency-analysis testing.frequency-analysis
