image: archlinux/base


stages:
    - builds
    - unit-tests
    - integration-tests


monoalphabetic-substitution-cipher-build:
    stage: builds
    before_script:
        - pacman -sy --noconfirm
        - pacman -s base-devel rust --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/monoalphabetic-substitution-cipher
        - cargo build


monoalphabetic-substitution-cipher-frequency-analysis-build:
    stage: builds
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/frequency-analysis
        - cargo build


monoalphabetic-substitution-cipher-unit-test:
    stage: unit-tests
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/monoalphabetic-substitution-cipher
        - cargo test


monoalphabetic-substitution-cipher-frequency-analysis-unit-test:
    stage: unit-tests
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel rust --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/frequency-analysis
        - cargo test


monoalphabetic-substitution-cipher-integration-test:
    stage: integration-tests 
    before_script:
        - pacman -sy --noconfirm
        - pacman -s base-devel rust diffutils --noconfirm
    script:
        - cd monoalphabetic-substitution-cipher/monoalphabetic-substitution-cipher
        - cargo build --release
        - target/release/monoalphabetic-substitution-cipher --key ../examples/The-Adventures-of-Sherlock-Holmes.key --input ../examples/The-Adventures-of-Sherlock-Holmes.plaintext > testing.ciphertext
        - cmp --silent ../examples/The-Adventures-of-Sherlock-Holmes.ciphertext testing.ciphertext 
