image: archlinux/base

stages:
    - build

build:
    stage: build
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel --noconfirm
        - pacman -S rust --noconfirm 
    script:
        - cd monoalphabetic-substitution-cipher/ 
        - cd monoalphabetic-substitution-cipher/ 
        - cargo build
        - cargo test
        - cd ../
        - cd frequency-analysis/
        - cargo build
        - cargo test

